package letsencrypt

import (
	"context"

	"github.com/go-acme/lego/v5/challenge"

	"github.com/lucasdillmann/nginx-ignition/internal/business/core/coreerror"
	"github.com/lucasdillmann/nginx-ignition/internal/business/core/i18n"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/abion"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/acmedns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/active24"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/alibaba"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/aliesa"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/allinkl"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/alwaysdata"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/anexia"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/artfiles"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/arvancloud"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/auroradns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/autodns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/aws"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/axelname"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/azion"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/azure"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/baiducloud"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/beget"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/binarylane"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/bindman"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/bluecat"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/bluecatv2"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/bookmyname"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/bunny"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/checkdomain"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/civo"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/clouddns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/cloudflare"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/cloudns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/cloudru"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/com35"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/connbyte"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/conohav2"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/conohav3"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/constellix"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/corenetworks"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/cpanel"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/curanet"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/czechia"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dandomain"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/ddnss"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/derak"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/desec"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/designate"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/digitalocean"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dinahosting"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/directadmin"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dns51"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dnscale"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dnsexit"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dnshomede"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dnsimple"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dnsla"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dnsmadeeasy"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dnsservices"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dode"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/domeneshop"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dreamhost"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/duckdns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dyn"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dynadot"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dyndnsfree"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/dynu"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/easydns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/edgecenter"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/edgedns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/edgeone"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/efficientip"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/epik"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/eurodns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/euserv"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/excedo"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/exec"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/exoscale"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/f5xc"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/fornex"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/freemyip"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/gandi"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/gandiv5"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/gcore"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/gcp"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/gehirn"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/gigahostno"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/glesys"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/gname"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/godaddy"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/gravity"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/hetzner"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/hostingde"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/hostinger"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/hostingnl"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/hosttech"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/hostup"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/httpnet"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/httpreq"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/huaweicloud"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/hurricane"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/hyperone"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/ibmcloud"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/iijdpf"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/infoblox"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/infomaniak"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/internetbs" //nolint:misspell
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/inwx"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/ionos"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/ionoscloud"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/ipv64"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/ispconfig"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/ispconfigddns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/jdcloud"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/joker"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/katapult"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/keyhelp"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/leaseweb"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/liara"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/lightsail"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/limacity"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/linode"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/liquidweb"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/loopia"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/luadns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/mailinabox"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/manageengine"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/metaname"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/metaregistrar"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/mijnhost"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/mittwald"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/myaddr"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/mydnsjp"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/mythicbeasts"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/namecheap"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/namedotcom"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/namesilo"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/namesurfer"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/nearlyfreespeech"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/nederhost"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/neodigit"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/netcup"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/netlify"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/netnod"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/nexdns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/ngenix"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/nicmanager"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/nicru"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/nifcloud"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/njalla"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/nodion"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/ns1"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/octenium"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/omglol"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/onecloudru"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/onlinenet"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/openprovider"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/opusdns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/oraclecloud"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/otc"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/ovh"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/pdns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/plesk"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/pointdns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/porkbun"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/poweradmin"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/rackspace"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/rage4"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/rainyun"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/rcodezero"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/regfish"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/regru"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/rfc2136"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/rimuhosting"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/safedns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/sakuracloud"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/scaleway"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/scannet"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/selectel"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/selectelv2"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/selfhostde"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/servercow"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/shellrent"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/simply"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/sonic"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/spaceship"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/syse"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/technitium"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/tele3"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/tencentcloud"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/timewebcloud"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/todaynic"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/transip"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/ucloud"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/ultradns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/uniteddomains"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/variomedia"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/veesp"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/vegadns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/vercel"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/versio"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/vinyldns"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/virtualname"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/vkcloud"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/volcengine"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/vscale"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/vultr"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/wannafind"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/webnamesca"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/webnamesru"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/websupport"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/wedos"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/westcn"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/xinnet"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/yandex"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/yandex360"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/yandexcloud"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/zilore"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/zoneedit"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/zoneee"
	"github.com/lucasdillmann/nginx-ignition/internal/certificate/domain/letsencrypt/dns/zonomi"
	//nolint:misspell
)

var providers = []dns.Provider{
	&acmedns.Provider{},
	&abion.Provider{},
	&active24.Provider{},
	&alibaba.Provider{},
	&aliesa.Provider{},
	&allinkl.Provider{},
	&alwaysdata.Provider{},
	&anexia.Provider{},
	&artfiles.Provider{},
	&arvancloud.Provider{},
	&auroradns.Provider{},
	&autodns.Provider{},
	&aws.Provider{},
	&axelname.Provider{},
	&azion.Provider{},
	&azure.Provider{},
	&baiducloud.Provider{},
	&beget.Provider{},
	&binarylane.Provider{},
	&bindman.Provider{},
	&bluecat.Provider{},
	&bluecatv2.Provider{},
	&bookmyname.Provider{},
	&bunny.Provider{},
	&checkdomain.Provider{},
	&civo.Provider{},
	&clouddns.Provider{},
	&cloudflare.Provider{},
	&cloudns.Provider{},
	&cloudru.Provider{},
	&com35.Provider{},
	&conohav2.Provider{},
	&conohav3.Provider{},
	&connbyte.Provider{},
	&constellix.Provider{},
	&corenetworks.Provider{},
	&cpanel.Provider{},
	&curanet.Provider{},
	&czechia.Provider{},
	&dandomain.Provider{},
	&ddnss.Provider{},
	&derak.Provider{},
	&desec.Provider{},
	&designate.Provider{},
	&digitalocean.Provider{},
	&dinahosting.Provider{},
	&directadmin.Provider{},
	&dnsexit.Provider{},
	&dnshomede.Provider{},
	&dns51.Provider{},
	&dnsimple.Provider{},
	&dnsla.Provider{},
	&dnsmadeeasy.Provider{},
	&dnscale.Provider{},
	&dnsservices.Provider{},
	&dode.Provider{},
	&domeneshop.Provider{},
	&dreamhost.Provider{},
	&duckdns.Provider{},
	&dyn.Provider{},
	&dynadot.Provider{},
	&dyndnsfree.Provider{},
	&dynu.Provider{},
	&easydns.Provider{},
	&edgecenter.Provider{},
	&edgedns.Provider{},
	&edgeone.Provider{},
	&efficientip.Provider{},
	&epik.Provider{},
	&eurodns.Provider{},
	&euserv.Provider{},
	&excedo.Provider{},
	&exec.Provider{},
	&exoscale.Provider{},
	&f5xc.Provider{},
	&fornex.Provider{},
	&freemyip.Provider{},
	&gandi.Provider{},
	&gandiv5.Provider{},
	&gcore.Provider{},
	&gcp.Provider{},
	&gehirn.Provider{},
	&gigahostno.Provider{},
	&glesys.Provider{},
	&gname.Provider{},
	&godaddy.Provider{},
	&gravity.Provider{},
	&hetzner.Provider{},
	&hostingde.Provider{},
	&hostinger.Provider{},
	&hostingnl.Provider{},
	&hosttech.Provider{},
	&hostup.Provider{},
	&httpnet.Provider{},
	&httpreq.Provider{},
	&huaweicloud.Provider{},
	&hurricane.Provider{},
	&hyperone.Provider{},
	&ibmcloud.Provider{},
	&iijdpf.Provider{},
	&infoblox.Provider{},
	&infomaniak.Provider{},
	&internetbs.Provider{}, //nolint:misspell
	&inwx.Provider{},
	&ionos.Provider{},
	&ionoscloud.Provider{},
	&ipv64.Provider{},
	&ispconfig.Provider{},
	&ispconfigddns.Provider{},
	&jdcloud.Provider{},
	&joker.Provider{},
	&katapult.Provider{},
	&keyhelp.Provider{},
	&leaseweb.Provider{},
	&liara.Provider{},
	&lightsail.Provider{},
	&limacity.Provider{},
	&linode.Provider{},
	&liquidweb.Provider{},
	&loopia.Provider{},
	&luadns.Provider{},
	&mailinabox.Provider{},
	&manageengine.Provider{},
	&metaname.Provider{},
	&metaregistrar.Provider{},
	&mijnhost.Provider{},
	&mittwald.Provider{},
	&myaddr.Provider{},
	&mydnsjp.Provider{},
	&mythicbeasts.Provider{},
	&namecheap.Provider{},
	&namedotcom.Provider{},
	&namesilo.Provider{},
	&namesurfer.Provider{},
	&nearlyfreespeech.Provider{},
	&nederhost.Provider{},
	&neodigit.Provider{},
	&netcup.Provider{},
	&netlify.Provider{},
	&netnod.Provider{},
	&nexdns.Provider{},
	&ngenix.Provider{},
	&nicmanager.Provider{},
	&nicru.Provider{},
	&nifcloud.Provider{},
	&njalla.Provider{},
	&nodion.Provider{},
	&ns1.Provider{},
	&octenium.Provider{},
	&omglol.Provider{},
	&onecloudru.Provider{},
	&onlinenet.Provider{},
	&openprovider.Provider{},
	&opusdns.Provider{},
	&oraclecloud.Provider{},
	&otc.Provider{},
	&ovh.Provider{},
	&pdns.Provider{},
	&pointdns.Provider{},
	&plesk.Provider{},
	&porkbun.Provider{},
	&poweradmin.Provider{},
	&rackspace.Provider{},
	&rage4.Provider{},
	&rainyun.Provider{},
	&rcodezero.Provider{},
	&regfish.Provider{},
	&regru.Provider{},
	&rfc2136.Provider{},
	&rimuhosting.Provider{},
	&safedns.Provider{},
	&sakuracloud.Provider{},
	&scaleway.Provider{},
	&scannet.Provider{},
	&selectel.Provider{},
	&selectelv2.Provider{},
	&selfhostde.Provider{},
	&servercow.Provider{},
	&shellrent.Provider{},
	&simply.Provider{},
	&sonic.Provider{},
	&spaceship.Provider{},
	&syse.Provider{},
	&technitium.Provider{},
	&tele3.Provider{},
	&tencentcloud.Provider{},
	&timewebcloud.Provider{},
	&todaynic.Provider{},
	&transip.Provider{},
	&ucloud.Provider{},
	&ultradns.Provider{},
	&uniteddomains.Provider{},
	&variomedia.Provider{},
	&veesp.Provider{},
	&vegadns.Provider{},
	&vercel.Provider{},
	&versio.Provider{},
	&vinyldns.Provider{},
	&virtualname.Provider{},
	&vkcloud.Provider{},
	&volcengine.Provider{},
	&vscale.Provider{},
	&vultr.Provider{},
	&wannafind.Provider{},
	&webnamesca.Provider{},
	&webnamesru.Provider{},
	&websupport.Provider{},
	&wedos.Provider{},
	&westcn.Provider{},
	&xinnet.Provider{},
	&yandex.Provider{},
	&yandex360.Provider{},
	&yandexcloud.Provider{},
	&zilore.Provider{},
	&zoneedit.Provider{},
	&zoneee.Provider{},
	&zonomi.Provider{},
}

func resolveProviderChallenge(
	ctx context.Context,
	domainNames []string,
	parameters map[string]any,
) (challenge.Provider, error) {
	providerID, _ := parameters[dnsProviderFieldID].(string)

	for _, provider := range providers {
		if provider.ID() == providerID {
			return provider.ChallengeProvider(ctx, domainNames, parameters)
		}
	}

	return nil, coreerror.New(
		i18n.M(ctx, i18n.K.CertificateLetsencryptUnknownDnsProvider),
		true,
	)
}
