package backup

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/JCoupalK/go-pgdump"

	"github.com/lucasdillmann/nginx-ignition/internal/business/core/configuration"
	backup2 "github.com/lucasdillmann/nginx-ignition/internal/business/domain/backup"
	"github.com/lucasdillmann/nginx-ignition/internal/database/core/database"
)

type repository struct {
	db     *database.Database
	config *configuration.Configuration
}

func New(
	db *database.Database,
	config *configuration.Configuration,
) backup2.Repository {
	return &repository{
		db:     db,
		config: config.WithPrefix("nginx-ignition.database"),
	}
}

func (r *repository) Get(_ context.Context) (*backup2.Backup, error) {
	driver, err := r.config.Get("driver")
	if err != nil {
		return nil, err
	}

	switch driver {
	case "sqlite":
		return r.getSqliteBackup()
	case "postgres":
		return r.getPostgresBackup()
	default:
		return nil, fmt.Errorf("unsupported database driver: %s", driver)
	}
}

func (r *repository) getSqliteBackup() (*backup2.Backup, error) {
	fileName := "nginx-ignition.db"

	folder, err := r.config.Get("data-path")
	if err != nil {
		return nil, err
	}

	//nolint:gosec // G304: filePath is constructed from a configured base path and a hardcoded filename
	filePath := filepath.Join(folder, fileName)
	contents, err := os.ReadFile(filePath)
	if err != nil {
		return nil, err
	}

	return &backup2.Backup{
		FileName:    fileName,
		ContentType: "application/x-sqlite3",
		Contents:    contents,
	}, nil
}

func (r *repository) getPostgresBackup() (*backup2.Backup, error) {
	tempFile, err := os.CreateTemp(os.TempDir(), "nginx-ignition.sql")
	if err != nil {
		return nil, err
	}

	//nolint:errcheck
	defer os.Remove(tempFile.Name())
	//nolint:errcheck
	defer tempFile.Close()

	dumper := pgdump.NewDumper(r.db.ConnectionString(), 1)
	if err = dumper.DumpDatabase(tempFile.Name(), &pgdump.TableOptions{}); err != nil {
		return nil, err
	}

	//nolint:gosec // G703: tempFile.Name() is generated by os.CreateTemp and is safe
	contents, err := os.ReadFile(tempFile.Name())
	if err != nil {
		return nil, err
	}

	return &backup2.Backup{
		FileName:    "nginx-ignition.sql",
		ContentType: "text/plain",
		Contents:    contents,
	}, nil
}
