# THIS IS AN EXAMPLE FILE
# Do not deploy it as is. Please review and update all values accordingly.

services:
  postgres:
    image: postgres:18-alpine
    container_name: nginx-ignition-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nginx_ignition
      POSTGRES_USER: nginx_ignition

      # DO NOT USE THIS PASSWORD VALUE IN A PRODUCTION ENVIRONMENT
      # Remember to change to a strong and secret password before deployment
      POSTGRES_PASSWORD: PlaceYourSuperSecretDatabasePasswordHere
    volumes:
      - nginx-ignition_postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nginx_ignition"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - nginx-ignition_default

  nginx-ignition:
    image: dillmann/nginx-ignition:latest
    container_name: nginx-ignition-app
    restart: unless-stopped
    ports:
      - "8090:8090"
      - "80:80"
      - "443:443"
    environment:
      NGINX_IGNITION_DATABASE_DRIVER: postgres
      NGINX_IGNITION_DATABASE_HOST: postgres
      NGINX_IGNITION_DATABASE_PORT: 5432
      NGINX_IGNITION_DATABASE_NAME: nginx_ignition
      NGINX_IGNITION_DATABASE_SSL_MODE: disable
      NGINX_IGNITION_DATABASE_USERNAME: nginx_ignition

      # DO NOT USE THIS PASSWORD VALUE IN A PRODUCTION ENVIRONMENT
      # Remember to change to a strong and secret password before deployment. It must be the same password you used
      # for the PostgreSQL database above.
      NGINX_IGNITION_DATABASE_PASSWORD: PlaceYourSuperSecretDatabasePasswordHere

      # DO NOT USE THIS SECRET VALUE IN A PRODUCTION ENVIRONMENT
      # Remember to change to a strong and secret key exactly 64 characters long before deployment.
      # For more details, please check the docs/configuration-properties.md file.
      NGINX_IGNITION_SECURITY_JWT_SECRET: PlaceYourSecretJwtPrivateKeyHereButRememberThatShouldHave64Chars
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health/liveness"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - nginx-ignition_default

networks:
  nginx-ignition_default:
    driver: bridge

volumes:
  nginx-ignition_postgres-data:
    driver: local
