sonar.organization=lucasdillmann
sonar.projectKey=lucasdillmann_nginx-ignition
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=\
  **/node_modules/**, \
  **/vendor/**, \
  **/.go/pkg/**, \
  **/*_test.go
sonar.coverage.exclusions=\
  **/*.mock.go, \
  **/*.generated.go, \
  **/*_test.go, \
  database/common/migrations/**, \
  frontend/**
sonar.go.coverage.reportPaths=coverage.out
sonar.cpd.exclusions=\
  database/common/migrations/**, \
  certificate/letsencrypt/dns/**, \
  vpn/**, \
  api/**, \
  **/*_test.go
