package configuration

var defaultValues = map[string]string{
	"nginx-ignition.server.port":                                   "8090",
	"nginx-ignition.server.address":                                "0.0.0.0",
	"nginx-ignition.server.read-timeout-seconds":                   "15",
	"nginx-ignition.server.write-timeout-seconds":                  "30",
	"nginx-ignition.server.idle-timeout-seconds":                   "120",
	"nginx-ignition.server.read-header-timeout-seconds":            "2",
	"nginx-ignition.server.max-header-bytes":                       "16384",
	"nginx-ignition.server.max-body-bytes":                         "10485760",
	"nginx-ignition.health-check.enabled":                          "true",
	"nginx-ignition.nginx.binary-path":                             "nginx",
	"nginx-ignition.nginx.config-path":                             "/tmp/nginx-ignition/nginx",
	"nginx-ignition.vpn.config-path":                               "/tmp/nginx-ignition/vpn",
	"nginx-ignition.database.driver":                               "sqlite",
	"nginx-ignition.database.data-path":                            "/tmp/nginx-ignition/data",
	"nginx-ignition.security.user-password-hashing.algorithm":      "SHA-512",
	"nginx-ignition.security.user-password-hashing.salt-size":      "64",
	"nginx-ignition.security.user-password-hashing.iterations":     "1024",
	"nginx-ignition.security.jwt.secret":                           "",
	"nginx-ignition.security.jwt.ttl-seconds":                      "3600",
	"nginx-ignition.security.jwt.clock-skew-seconds":               "60",
	"nginx-ignition.security.jwt.renew-window-seconds":             "900",
	"nginx-ignition.certificate.lets-encrypt.production":           "true",
	"nginx-ignition.integration.truenas.api-cache-timeout-seconds": "15",
	"nginx-ignition.password-reset.username":                       "",
}
