package main

const goKeyFileTemplate = `//golang:generated Generated by tools/i18n
package i18n

var Keys = struct {
{{- range .Items }}
	{{.ConstName}} string
{{- end }}
} {
{{- range .Items }}
	{{.ConstName}}: "{{.Value}}",
{{- end }}
}
`

const tsKeyFileTemplate = `//ts:generated Generated by tools/i18n

enum MessageKey {
{{- range .Items }}
	{{.ConstName}} = "{{.Value}}",
{{- end }}
}

export default MessageKey
`

const dictionaryFileTemplate = `//golang:generated Generated by tools/i18n
package i18n

import (
	"golang.org/x/text/language"
)

func {{.FuncName}}() Dictionary {
	return newDictionary(
		language.Make("{{.LangTag}}"),
		map[string]string{
{{- range .Keys }}
			Keys.{{.ConstName}}: "{{.Value}}",
{{- end }}
		},
	)
}
`
